# Generated by Django 2.1.3 on 2018-11-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatorskill',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='curatorskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='student',
        ),
        migrations.RemoveField(
            model_name='themeskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='themeskill',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='curator',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='curator',
            name='skills1',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills1',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='theme',
            name='required_skills1',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.DeleteModel(
            name='CuratorSkill',
        ),
        migrations.DeleteModel(
            name='StudentSkill',
        ),
        migrations.DeleteModel(
            name='ThemeSkill',
        ),
    ]
