# Generated by Django 2.1.3 on 2018-11-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181108_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curator',
            old_name='skills1',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='skills1',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='required_skills1',
            new_name='required_skills',
        ),
    ]
